# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dooz/projects/roguelike

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dooz/projects/roguelike

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dooz/projects/roguelike/CMakeFiles /Users/dooz/projects/roguelike/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dooz/projects/roguelike/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named roguelike

# Build rule for target.
roguelike: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 roguelike
.PHONY : roguelike

# fast build rule for target.
roguelike/fast:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/build
.PHONY : roguelike/fast

animated_sprite.o: animated_sprite.cpp.o
.PHONY : animated_sprite.o

# target to build an object file
animated_sprite.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animated_sprite.cpp.o
.PHONY : animated_sprite.cpp.o

animated_sprite.i: animated_sprite.cpp.i
.PHONY : animated_sprite.i

# target to preprocess a source file
animated_sprite.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animated_sprite.cpp.i
.PHONY : animated_sprite.cpp.i

animated_sprite.s: animated_sprite.cpp.s
.PHONY : animated_sprite.s

# target to generate assembly for a file
animated_sprite.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animated_sprite.cpp.s
.PHONY : animated_sprite.cpp.s

animation.o: animation.cpp.o
.PHONY : animation.o

# target to build an object file
animation.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animation.cpp.o
.PHONY : animation.cpp.o

animation.i: animation.cpp.i
.PHONY : animation.i

# target to preprocess a source file
animation.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animation.cpp.i
.PHONY : animation.cpp.i

animation.s: animation.cpp.s
.PHONY : animation.s

# target to generate assembly for a file
animation.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animation.cpp.s
.PHONY : animation.cpp.s

animation_manager.o: animation_manager.cpp.o
.PHONY : animation_manager.o

# target to build an object file
animation_manager.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animation_manager.cpp.o
.PHONY : animation_manager.cpp.o

animation_manager.i: animation_manager.cpp.i
.PHONY : animation_manager.i

# target to preprocess a source file
animation_manager.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animation_manager.cpp.i
.PHONY : animation_manager.cpp.i

animation_manager.s: animation_manager.cpp.s
.PHONY : animation_manager.s

# target to generate assembly for a file
animation_manager.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/animation_manager.cpp.s
.PHONY : animation_manager.cpp.s

debug_renderer.o: debug_renderer.cpp.o
.PHONY : debug_renderer.o

# target to build an object file
debug_renderer.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/debug_renderer.cpp.o
.PHONY : debug_renderer.cpp.o

debug_renderer.i: debug_renderer.cpp.i
.PHONY : debug_renderer.i

# target to preprocess a source file
debug_renderer.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/debug_renderer.cpp.i
.PHONY : debug_renderer.cpp.i

debug_renderer.s: debug_renderer.cpp.s
.PHONY : debug_renderer.s

# target to generate assembly for a file
debug_renderer.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/debug_renderer.cpp.s
.PHONY : debug_renderer.cpp.s

entity.o: entity.cpp.o
.PHONY : entity.o

# target to build an object file
entity.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/entity.cpp.o
.PHONY : entity.cpp.o

entity.i: entity.cpp.i
.PHONY : entity.i

# target to preprocess a source file
entity.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/entity.cpp.i
.PHONY : entity.cpp.i

entity.s: entity.cpp.s
.PHONY : entity.s

# target to generate assembly for a file
entity.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/entity.cpp.s
.PHONY : entity.cpp.s

error.o: error.cpp.o
.PHONY : error.o

# target to build an object file
error.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/error.cpp.o
.PHONY : error.cpp.o

error.i: error.cpp.i
.PHONY : error.i

# target to preprocess a source file
error.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/error.cpp.i
.PHONY : error.cpp.i

error.s: error.cpp.s
.PHONY : error.s

# target to generate assembly for a file
error.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/error.cpp.s
.PHONY : error.cpp.s

game.o: game.cpp.o
.PHONY : game.o

# target to build an object file
game.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game.cpp.o
.PHONY : game.cpp.o

game.i: game.cpp.i
.PHONY : game.i

# target to preprocess a source file
game.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game.cpp.i
.PHONY : game.cpp.i

game.s: game.cpp.s
.PHONY : game.s

# target to generate assembly for a file
game.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game.cpp.s
.PHONY : game.cpp.s

game_ai.o: game_ai.cpp.o
.PHONY : game_ai.o

# target to build an object file
game_ai.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_ai.cpp.o
.PHONY : game_ai.cpp.o

game_ai.i: game_ai.cpp.i
.PHONY : game_ai.i

# target to preprocess a source file
game_ai.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_ai.cpp.i
.PHONY : game_ai.cpp.i

game_ai.s: game_ai.cpp.s
.PHONY : game_ai.s

# target to generate assembly for a file
game_ai.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_ai.cpp.s
.PHONY : game_ai.cpp.s

game_event_manager.o: game_event_manager.cpp.o
.PHONY : game_event_manager.o

# target to build an object file
game_event_manager.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_event_manager.cpp.o
.PHONY : game_event_manager.cpp.o

game_event_manager.i: game_event_manager.cpp.i
.PHONY : game_event_manager.i

# target to preprocess a source file
game_event_manager.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_event_manager.cpp.i
.PHONY : game_event_manager.cpp.i

game_event_manager.s: game_event_manager.cpp.s
.PHONY : game_event_manager.s

# target to generate assembly for a file
game_event_manager.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_event_manager.cpp.s
.PHONY : game_event_manager.cpp.s

game_player.o: game_player.cpp.o
.PHONY : game_player.o

# target to build an object file
game_player.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_player.cpp.o
.PHONY : game_player.cpp.o

game_player.i: game_player.cpp.i
.PHONY : game_player.i

# target to preprocess a source file
game_player.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_player.cpp.i
.PHONY : game_player.cpp.i

game_player.s: game_player.cpp.s
.PHONY : game_player.s

# target to generate assembly for a file
game_player.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_player.cpp.s
.PHONY : game_player.cpp.s

game_state.o: game_state.cpp.o
.PHONY : game_state.o

# target to build an object file
game_state.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_state.cpp.o
.PHONY : game_state.cpp.o

game_state.i: game_state.cpp.i
.PHONY : game_state.i

# target to preprocess a source file
game_state.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_state.cpp.i
.PHONY : game_state.cpp.i

game_state.s: game_state.cpp.s
.PHONY : game_state.s

# target to generate assembly for a file
game_state.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/game_state.cpp.s
.PHONY : game_state.cpp.s

hotload_sprite.o: hotload_sprite.cpp.o
.PHONY : hotload_sprite.o

# target to build an object file
hotload_sprite.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/hotload_sprite.cpp.o
.PHONY : hotload_sprite.cpp.o

hotload_sprite.i: hotload_sprite.cpp.i
.PHONY : hotload_sprite.i

# target to preprocess a source file
hotload_sprite.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/hotload_sprite.cpp.i
.PHONY : hotload_sprite.cpp.i

hotload_sprite.s: hotload_sprite.cpp.s
.PHONY : hotload_sprite.s

# target to generate assembly for a file
hotload_sprite.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/hotload_sprite.cpp.s
.PHONY : hotload_sprite.cpp.s

level.o: level.cpp.o
.PHONY : level.o

# target to build an object file
level.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/level.cpp.o
.PHONY : level.cpp.o

level.i: level.cpp.i
.PHONY : level.i

# target to preprocess a source file
level.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/level.cpp.i
.PHONY : level.cpp.i

level.s: level.cpp.s
.PHONY : level.s

# target to generate assembly for a file
level.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/level.cpp.s
.PHONY : level.cpp.s

level_factory.o: level_factory.cpp.o
.PHONY : level_factory.o

# target to build an object file
level_factory.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/level_factory.cpp.o
.PHONY : level_factory.cpp.o

level_factory.i: level_factory.cpp.i
.PHONY : level_factory.i

# target to preprocess a source file
level_factory.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/level_factory.cpp.i
.PHONY : level_factory.cpp.i

level_factory.s: level_factory.cpp.s
.PHONY : level_factory.s

# target to generate assembly for a file
level_factory.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/level_factory.cpp.s
.PHONY : level_factory.cpp.s

loot_item.o: loot_item.cpp.o
.PHONY : loot_item.o

# target to build an object file
loot_item.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/loot_item.cpp.o
.PHONY : loot_item.cpp.o

loot_item.i: loot_item.cpp.i
.PHONY : loot_item.i

# target to preprocess a source file
loot_item.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/loot_item.cpp.i
.PHONY : loot_item.cpp.i

loot_item.s: loot_item.cpp.s
.PHONY : loot_item.s

# target to generate assembly for a file
loot_item.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/loot_item.cpp.s
.PHONY : loot_item.cpp.s

monster.o: monster.cpp.o
.PHONY : monster.o

# target to build an object file
monster.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/monster.cpp.o
.PHONY : monster.cpp.o

monster.i: monster.cpp.i
.PHONY : monster.i

# target to preprocess a source file
monster.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/monster.cpp.i
.PHONY : monster.cpp.i

monster.s: monster.cpp.s
.PHONY : monster.s

# target to generate assembly for a file
monster.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/monster.cpp.s
.PHONY : monster.cpp.s

party.o: party.cpp.o
.PHONY : party.o

# target to build an object file
party.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/party.cpp.o
.PHONY : party.cpp.o

party.i: party.cpp.i
.PHONY : party.i

# target to preprocess a source file
party.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/party.cpp.i
.PHONY : party.cpp.i

party.s: party.cpp.s
.PHONY : party.s

# target to generate assembly for a file
party.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/party.cpp.s
.PHONY : party.cpp.s

player.o: player.cpp.o
.PHONY : player.o

# target to build an object file
player.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/player.cpp.o
.PHONY : player.cpp.o

player.i: player.cpp.i
.PHONY : player.i

# target to preprocess a source file
player.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/player.cpp.i
.PHONY : player.cpp.i

player.s: player.cpp.s
.PHONY : player.s

# target to generate assembly for a file
player.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/player.cpp.s
.PHONY : player.cpp.s

player_factory.o: player_factory.cpp.o
.PHONY : player_factory.o

# target to build an object file
player_factory.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/player_factory.cpp.o
.PHONY : player_factory.cpp.o

player_factory.i: player_factory.cpp.i
.PHONY : player_factory.i

# target to preprocess a source file
player_factory.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/player_factory.cpp.i
.PHONY : player_factory.cpp.i

player_factory.s: player_factory.cpp.s
.PHONY : player_factory.s

# target to generate assembly for a file
player_factory.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/player_factory.cpp.s
.PHONY : player_factory.cpp.s

precompiled.o: precompiled.cpp.o
.PHONY : precompiled.o

# target to build an object file
precompiled.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/precompiled.cpp.o
.PHONY : precompiled.cpp.o

precompiled.i: precompiled.cpp.i
.PHONY : precompiled.i

# target to preprocess a source file
precompiled.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/precompiled.cpp.i
.PHONY : precompiled.cpp.i

precompiled.s: precompiled.cpp.s
.PHONY : precompiled.s

# target to generate assembly for a file
precompiled.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/precompiled.cpp.s
.PHONY : precompiled.cpp.s

protocol/animation_config.pb.o: protocol/animation_config.pb.cc.o
.PHONY : protocol/animation_config.pb.o

# target to build an object file
protocol/animation_config.pb.cc.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/animation_config.pb.cc.o
.PHONY : protocol/animation_config.pb.cc.o

protocol/animation_config.pb.i: protocol/animation_config.pb.cc.i
.PHONY : protocol/animation_config.pb.i

# target to preprocess a source file
protocol/animation_config.pb.cc.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/animation_config.pb.cc.i
.PHONY : protocol/animation_config.pb.cc.i

protocol/animation_config.pb.s: protocol/animation_config.pb.cc.s
.PHONY : protocol/animation_config.pb.s

# target to generate assembly for a file
protocol/animation_config.pb.cc.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/animation_config.pb.cc.s
.PHONY : protocol/animation_config.pb.cc.s

protocol/spell_config.pb.o: protocol/spell_config.pb.cc.o
.PHONY : protocol/spell_config.pb.o

# target to build an object file
protocol/spell_config.pb.cc.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/spell_config.pb.cc.o
.PHONY : protocol/spell_config.pb.cc.o

protocol/spell_config.pb.i: protocol/spell_config.pb.cc.i
.PHONY : protocol/spell_config.pb.i

# target to preprocess a source file
protocol/spell_config.pb.cc.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/spell_config.pb.cc.i
.PHONY : protocol/spell_config.pb.cc.i

protocol/spell_config.pb.s: protocol/spell_config.pb.cc.s
.PHONY : protocol/spell_config.pb.s

# target to generate assembly for a file
protocol/spell_config.pb.cc.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/spell_config.pb.cc.s
.PHONY : protocol/spell_config.pb.cc.s

protocol/sprite.pb.o: protocol/sprite.pb.cc.o
.PHONY : protocol/sprite.pb.o

# target to build an object file
protocol/sprite.pb.cc.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/sprite.pb.cc.o
.PHONY : protocol/sprite.pb.cc.o

protocol/sprite.pb.i: protocol/sprite.pb.cc.i
.PHONY : protocol/sprite.pb.i

# target to preprocess a source file
protocol/sprite.pb.cc.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/sprite.pb.cc.i
.PHONY : protocol/sprite.pb.cc.i

protocol/sprite.pb.s: protocol/sprite.pb.cc.s
.PHONY : protocol/sprite.pb.s

# target to generate assembly for a file
protocol/sprite.pb.cc.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/protocol/sprite.pb.cc.s
.PHONY : protocol/sprite.pb.cc.s

renderer.o: renderer.cpp.o
.PHONY : renderer.o

# target to build an object file
renderer.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/renderer.cpp.o
.PHONY : renderer.cpp.o

renderer.i: renderer.cpp.i
.PHONY : renderer.i

# target to preprocess a source file
renderer.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/renderer.cpp.i
.PHONY : renderer.cpp.i

renderer.s: renderer.cpp.s
.PHONY : renderer.s

# target to generate assembly for a file
renderer.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/renderer.cpp.s
.PHONY : renderer.cpp.s

roguelike.o: roguelike.cpp.o
.PHONY : roguelike.o

# target to build an object file
roguelike.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/roguelike.cpp.o
.PHONY : roguelike.cpp.o

roguelike.i: roguelike.cpp.i
.PHONY : roguelike.i

# target to preprocess a source file
roguelike.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/roguelike.cpp.i
.PHONY : roguelike.cpp.i

roguelike.s: roguelike.cpp.s
.PHONY : roguelike.s

# target to generate assembly for a file
roguelike.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/roguelike.cpp.s
.PHONY : roguelike.cpp.s

shapes.o: shapes.cpp.o
.PHONY : shapes.o

# target to build an object file
shapes.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/shapes.cpp.o
.PHONY : shapes.cpp.o

shapes.i: shapes.cpp.i
.PHONY : shapes.i

# target to preprocess a source file
shapes.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/shapes.cpp.i
.PHONY : shapes.cpp.i

shapes.s: shapes.cpp.s
.PHONY : shapes.s

# target to generate assembly for a file
shapes.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/shapes.cpp.s
.PHONY : shapes.cpp.s

spell.o: spell.cpp.o
.PHONY : spell.o

# target to build an object file
spell.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/spell.cpp.o
.PHONY : spell.cpp.o

spell.i: spell.cpp.i
.PHONY : spell.i

# target to preprocess a source file
spell.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/spell.cpp.i
.PHONY : spell.cpp.i

spell.s: spell.cpp.s
.PHONY : spell.s

# target to generate assembly for a file
spell.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/spell.cpp.s
.PHONY : spell.cpp.s

standard_cursor.o: standard_cursor.cpp.o
.PHONY : standard_cursor.o

# target to build an object file
standard_cursor.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/standard_cursor.cpp.o
.PHONY : standard_cursor.cpp.o

standard_cursor.i: standard_cursor.cpp.i
.PHONY : standard_cursor.i

# target to preprocess a source file
standard_cursor.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/standard_cursor.cpp.i
.PHONY : standard_cursor.cpp.i

standard_cursor.s: standard_cursor.cpp.s
.PHONY : standard_cursor.s

# target to generate assembly for a file
standard_cursor.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/standard_cursor.cpp.s
.PHONY : standard_cursor.cpp.s

texture_cache.o: texture_cache.cpp.o
.PHONY : texture_cache.o

# target to build an object file
texture_cache.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/texture_cache.cpp.o
.PHONY : texture_cache.cpp.o

texture_cache.i: texture_cache.cpp.i
.PHONY : texture_cache.i

# target to preprocess a source file
texture_cache.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/texture_cache.cpp.i
.PHONY : texture_cache.cpp.i

texture_cache.s: texture_cache.cpp.s
.PHONY : texture_cache.s

# target to generate assembly for a file
texture_cache.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/texture_cache.cpp.s
.PHONY : texture_cache.cpp.s

texture_handle.o: texture_handle.cpp.o
.PHONY : texture_handle.o

# target to build an object file
texture_handle.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/texture_handle.cpp.o
.PHONY : texture_handle.cpp.o

texture_handle.i: texture_handle.cpp.i
.PHONY : texture_handle.i

# target to preprocess a source file
texture_handle.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/texture_handle.cpp.i
.PHONY : texture_handle.cpp.i

texture_handle.s: texture_handle.cpp.s
.PHONY : texture_handle.s

# target to generate assembly for a file
texture_handle.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/texture_handle.cpp.s
.PHONY : texture_handle.cpp.s

tile.o: tile.cpp.o
.PHONY : tile.o

# target to build an object file
tile.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/tile.cpp.o
.PHONY : tile.cpp.o

tile.i: tile.cpp.i
.PHONY : tile.i

# target to preprocess a source file
tile.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/tile.cpp.i
.PHONY : tile.cpp.i

tile.s: tile.cpp.s
.PHONY : tile.s

# target to generate assembly for a file
tile.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/tile.cpp.s
.PHONY : tile.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/utils.cpp.s
.PHONY : utils.cpp.s

virtual_window.o: virtual_window.cpp.o
.PHONY : virtual_window.o

# target to build an object file
virtual_window.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/virtual_window.cpp.o
.PHONY : virtual_window.cpp.o

virtual_window.i: virtual_window.cpp.i
.PHONY : virtual_window.i

# target to preprocess a source file
virtual_window.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/virtual_window.cpp.i
.PHONY : virtual_window.cpp.i

virtual_window.s: virtual_window.cpp.s
.PHONY : virtual_window.s

# target to generate assembly for a file
virtual_window.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/virtual_window.cpp.s
.PHONY : virtual_window.cpp.s

virtual_window_manager.o: virtual_window_manager.cpp.o
.PHONY : virtual_window_manager.o

# target to build an object file
virtual_window_manager.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/virtual_window_manager.cpp.o
.PHONY : virtual_window_manager.cpp.o

virtual_window_manager.i: virtual_window_manager.cpp.i
.PHONY : virtual_window_manager.i

# target to preprocess a source file
virtual_window_manager.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/virtual_window_manager.cpp.i
.PHONY : virtual_window_manager.cpp.i

virtual_window_manager.s: virtual_window_manager.cpp.s
.PHONY : virtual_window_manager.s

# target to generate assembly for a file
virtual_window_manager.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/virtual_window_manager.cpp.s
.PHONY : virtual_window_manager.cpp.s

window_event_manager.o: window_event_manager.cpp.o
.PHONY : window_event_manager.o

# target to build an object file
window_event_manager.cpp.o:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/window_event_manager.cpp.o
.PHONY : window_event_manager.cpp.o

window_event_manager.i: window_event_manager.cpp.i
.PHONY : window_event_manager.i

# target to preprocess a source file
window_event_manager.cpp.i:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/window_event_manager.cpp.i
.PHONY : window_event_manager.cpp.i

window_event_manager.s: window_event_manager.cpp.s
.PHONY : window_event_manager.s

# target to generate assembly for a file
window_event_manager.cpp.s:
	$(MAKE) -f CMakeFiles/roguelike.dir/build.make CMakeFiles/roguelike.dir/window_event_manager.cpp.s
.PHONY : window_event_manager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... roguelike"
	@echo "... animated_sprite.o"
	@echo "... animated_sprite.i"
	@echo "... animated_sprite.s"
	@echo "... animation.o"
	@echo "... animation.i"
	@echo "... animation.s"
	@echo "... animation_manager.o"
	@echo "... animation_manager.i"
	@echo "... animation_manager.s"
	@echo "... debug_renderer.o"
	@echo "... debug_renderer.i"
	@echo "... debug_renderer.s"
	@echo "... entity.o"
	@echo "... entity.i"
	@echo "... entity.s"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... game.o"
	@echo "... game.i"
	@echo "... game.s"
	@echo "... game_ai.o"
	@echo "... game_ai.i"
	@echo "... game_ai.s"
	@echo "... game_event_manager.o"
	@echo "... game_event_manager.i"
	@echo "... game_event_manager.s"
	@echo "... game_player.o"
	@echo "... game_player.i"
	@echo "... game_player.s"
	@echo "... game_state.o"
	@echo "... game_state.i"
	@echo "... game_state.s"
	@echo "... hotload_sprite.o"
	@echo "... hotload_sprite.i"
	@echo "... hotload_sprite.s"
	@echo "... level.o"
	@echo "... level.i"
	@echo "... level.s"
	@echo "... level_factory.o"
	@echo "... level_factory.i"
	@echo "... level_factory.s"
	@echo "... loot_item.o"
	@echo "... loot_item.i"
	@echo "... loot_item.s"
	@echo "... monster.o"
	@echo "... monster.i"
	@echo "... monster.s"
	@echo "... party.o"
	@echo "... party.i"
	@echo "... party.s"
	@echo "... player.o"
	@echo "... player.i"
	@echo "... player.s"
	@echo "... player_factory.o"
	@echo "... player_factory.i"
	@echo "... player_factory.s"
	@echo "... precompiled.o"
	@echo "... precompiled.i"
	@echo "... precompiled.s"
	@echo "... protocol/animation_config.pb.o"
	@echo "... protocol/animation_config.pb.i"
	@echo "... protocol/animation_config.pb.s"
	@echo "... protocol/spell_config.pb.o"
	@echo "... protocol/spell_config.pb.i"
	@echo "... protocol/spell_config.pb.s"
	@echo "... protocol/sprite.pb.o"
	@echo "... protocol/sprite.pb.i"
	@echo "... protocol/sprite.pb.s"
	@echo "... renderer.o"
	@echo "... renderer.i"
	@echo "... renderer.s"
	@echo "... roguelike.o"
	@echo "... roguelike.i"
	@echo "... roguelike.s"
	@echo "... shapes.o"
	@echo "... shapes.i"
	@echo "... shapes.s"
	@echo "... spell.o"
	@echo "... spell.i"
	@echo "... spell.s"
	@echo "... standard_cursor.o"
	@echo "... standard_cursor.i"
	@echo "... standard_cursor.s"
	@echo "... texture_cache.o"
	@echo "... texture_cache.i"
	@echo "... texture_cache.s"
	@echo "... texture_handle.o"
	@echo "... texture_handle.i"
	@echo "... texture_handle.s"
	@echo "... tile.o"
	@echo "... tile.i"
	@echo "... tile.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... virtual_window.o"
	@echo "... virtual_window.i"
	@echo "... virtual_window.s"
	@echo "... virtual_window_manager.o"
	@echo "... virtual_window_manager.i"
	@echo "... virtual_window_manager.s"
	@echo "... window_event_manager.o"
	@echo "... window_event_manager.i"
	@echo "... window_event_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

